### PR TITLE
Fixed a navigation problem in Home and Franchises

### LINKED ISSUE #60: Products not loading
## REQUIREMENTS / DESCRIPTION

> I cannot access the products information from Home or categories, I press a product and it doesn't show.

### PR DESCRIPTION
**Pull request by HenrikhWolf**
# Description

What did you implemented/Why did you implemented this:

- Fixed a problem that was preventing Home from showing the produc information screen.
- Implemented the navigation to the product information into the Categories/Franchises screen
- This following #60 

## Testing
- Since the project is just initialized you only need install the basic packages to visualize the application
```npm install```
- Then you can initialize with an android emulator or via web
```npm start```
- Login if you are registered
- Browse through the app
- Select any product to see its details

Help me how can I test or look at the changes

## Screenshots

imagen

### CODE REVIEW

File: src/navigation/loggedNav.jsx [hunk 1]
```diff
@@ -37,6 +37,33 @@ export default class LoggedNav extends Component {
...
+            headerRight: (props) => (
+              <AntDesign
+                name="shoppingcart"
+                size={30}
+                style={{ marginRight: 15 }}
+                color={props.tintColor}
+              />
+            ),
+          }}
+        />
```
Comment (yovanha) [inline src/navigation/loggedNav.jsx]: Check the indentation of this code

Comment (HenrikhWolf) [reply src/navigation/loggedNav.jsx]: Done, and I found another indentation problem in the other file and fixed it too

**Review by arthurchina92 — APPROVED** [review]

File: src/navigation/loggedNav.jsx [hunk 2]
```diff
@@ -37,6 +37,33 @@ export default class LoggedNav extends Component {
...
+          component={OnProductDetail}
+          options={{
+            headerShown: true,
+            headerBackVisible: false,
+            tabBarButton: () => null,
+            headerLeft: (props) => (
+              <FontAwesome5
+                onPress={() => this.props.navigation.navigate("UserProfile")}
+                name="user-circle"
+                style={{ marginLeft: 15 }}
```
Comment (YilKanda) [inline src/navigation/loggedNav.jsx]: The style can call it in an external file.

File: src/navigation/loggedNav.jsx [hunk 3]
```diff
@@ -37,6 +37,33 @@ export default class LoggedNav extends Component {
...
+                size={30}
+                color={props.tintColor}
+              />
+            ),
+            headerRight: (props) => (
+              <AntDesign
+                name="shoppingcart"
+                size={30}
+                style={{ marginRight: 15 }}
```
Comment (YilKanda) [inline src/navigation/loggedNav.jsx]: The style can call it in an external file.

File: src/navigation/loggedNav.jsx (hunk 2 above)
Comment (HenrikhWolf) [reply src/navigation/loggedNav.jsx]: Done

File: src/navigation/loggedNav.jsx (hunk 3 above)
Comment (HenrikhWolf) [reply src/navigation/loggedNav.jsx]: Done

**Review by Zuack55 — APPROVED** [review]
👍

**Review by YilKanda — APPROVED** [review]
